// Code generated by sqlc. DO NOT EDIT.
// source: student.sql

package db

import (
	"context"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (
  email, 
  name
) VALUES (
  $1, $2
)
RETURNING id, email, name, joined_at
`

type CreateStudentParams struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, createStudent, arg.Email, arg.Name)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.JoinedAt,
	)
	return i, err
}

const deleteStudent = `-- name: DeleteStudent :exec
DELETE FROM students
WHERE id = $1
`

func (q *Queries) DeleteStudent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStudent, id)
	return err
}

const getStudent = `-- name: GetStudent :one
SELECT id, email, name, joined_at FROM students
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStudent(ctx context.Context, id int64) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.JoinedAt,
	)
	return i, err
}

const listStudents = `-- name: ListStudents :many
SELECT id, email, name, joined_at FROM students
ORDER BY id
LIMIT $1 
OFFSET $2
`

type ListStudentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStudents(ctx context.Context, arg ListStudentsParams) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, listStudents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students 
SET 
  name = $2
WHERE id = $1
RETURNING id, email, name, joined_at
`

type UpdateStudentParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, updateStudent, arg.ID, arg.Name)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.JoinedAt,
	)
	return i, err
}
